### ISSUE TITLE
Suppress console logs no longer works as of Rails 5.1

### ISSUE THREAD

**Issue by jeffreyguenther** [LoamStudios/seed_tray#5]

**Comment by kieraneglin** [comment]
This is due to overzealous asset caching.  If you bust the cache (`rails tmp:cache:clear` or change a line in `seed_tray.js.coffee`), it will work as expected.

I'm looking into how to disable caching/fingerprinting for a single file from within a gem.  I'll make a PR if I come up with something fancy.

**Comment by jeffreyguenther** [comment]
Ah, yes. I didn't think to do that. That works. Let's call this closed for now and keep an eye out for a solution.
